# `docker-compose up --build` can be used to run. 
version: '3.8'

services:
  app:
    image: python:3.12
    container_name: weather_app
    working_dir: /app
    volumes:
      - .:/app
    clone:
      git: https://github.com/Math-Racer/PythonWeatherApp.git
    build:
      context: .
      dockerfile: Dockerfile.git
    ports:
      - "5000:5000"
    command: ["python", "app.py"]

